#ifndef DLL_QCORE_EXP1_GLOBAL_H
#define DLL_QCORE_EXP1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLL_QCORE_EXP1_LIBRARY)
#  define DLL_QCORE_EXP1_EXPORT Q_DECL_EXPORT
#else
#  define DLL_QCORE_EXP1_EXPORT Q_DECL_IMPORT
#endif

#endif // DLL_QCORE_EXP1_GLOBAL_H
